apiVersion: v1
kind: ConfigMap
metadata:
  name: kubero-config
  namespace: kubero
data:
  config.yaml: |
    kubero:
      namespace: kubero
      context: "in-cluster"
      port: 2000
      auditLogs: false
    buildpacks:
      - name: node
        language: NodeJS
        fetch:
          repository: node
          tag: latest
        build:
          repository: node
          tag: latest
          command: npm install
        run:
          repository: node
          tag: latest
          command: node server.js
    podSizeList:
      - name: small
        description: Small (0.25 CPU, 0.5Gi RAM)
        default: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubero
  namespace: kubero
  labels:
    app: kubero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubero
  template:
    metadata:
      labels:
        app: kubero
    spec:
      serviceAccountName: kubero
      containers:
      - name: kubero
        image: ghcr.io/kubero-dev/kubero/kubero:latest
        ports:
        - containerPort: 2000
        env:
        - name: KUBERO_NAMESPACE
          value: "kubero"
        - name: KUBERO_PORT
          value: "2000"
        - name: KUBERO_SESSION_KEY
          valueFrom:
            secretKeyRef:
              name: kubero-secrets
              key: KUBERO_SESSION_KEY
        - name: KUBERO_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: kubero-secrets
              key: KUBERO_WEBHOOK_SECRET
        - name: KUBERO_AUDIT_LOGS
          value: "false"
        volumeMounts:
        - name: config
          mountPath: /app/server/config.yaml
          subPath: config.yaml
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: config
        configMap:
          name: kubero-config
---
apiVersion: v1
kind: Service
metadata:
  name: kubero
  namespace: kubero
spec:
  type: NodePort
  selector:
    app: kubero
  ports:
  - port: 2000
    targetPort: 2000
    nodePort: 30010
    name: http
